Repository Ce11an/surrealql-lsp, pull requests merged in 2024-07, with the labels that each got.

#3 Completion progress
  crates/server/src/main.rs
Labels: enhancement

#4 Add Visual Studio Code client for debugging
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  editors/code/.eslintignore
  editors/code/.eslintrc.js
  editors/code/.gitignore
  editors/code/.vscodeignore
  editors/code/package-lock.json
  editors/code/package.json
  editors/code/src/extension.ts
  editors/code/tsconfig.json
  examples/test.surql
  package-lock.json
  test.surql
Labels: documentation, enhancement

#5 Added normalization of documents to support multlline completions
  crates/server/src/main.rs
Labels: enhancement

#6 Add CI, formatting, and linting
  .editorconfig
  .gitattributes
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/rust.json
  .github/workflows/ci.yaml
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  Cargo.toml
  LICENSE-APACHE
  LICENSE-MIT
  crates/server/Cargo.toml
  crates/server/src/main.rs
  crates/server/src/md/explain.md
  crates/server/src/md/from.md
  crates/server/src/md/group_by.md
  crates/server/src/md/limit.md
  crates/server/src/md/only.md
  crates/server/src/md/order_by.md
  crates/server/src/md/select.md
  crates/server/src/md/timeout.md
  crates/server/src/md/value.md
  crates/server/src/md/where.md
  crates/server/src/md/with.md
  editors/code/.eslintignore
  editors/code/.eslintrc.js
  editors/code/.gitignore
  editors/code/.vscodeignore
  editors/code/package-lock.json
  editors/code/package.json
  editors/code/src/extension.ts
  editors/code/tsconfig.json
  rust-toolchain.toml
  rustfmt.toml
Labels: enhancement

#7 Remove root-level `package.lock`
  package-lock.json
Labels: bug

#8 Add initial hover support
  crates/server/src/main.rs
Labels: enhancement

#9 Update README.md go include hover details
  README.md
  crates/server/src/main.rs
Labels: documentation
